# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork
  # default: mainnet


# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0
  - iearn-finance/yearn-vaults@0.2.2

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"
      - "@yearnvaultsV2=iearn-finance/yearn-vaults@0.2.2"

reports:
  exclude_contracts:
    - SafeMath
